// 一次性：startFight 改交互式回合制（行区间 302-383 替换，执行后自删）
const fs = require("fs");
const f = "public/games/shanhai/challenge.html";
const lines = fs.readFileSync(f, "utf8").split("\n");
// 行 302-383（1-based）→ 索引 301..382
const NEW = [
  '/* ===== 交互式回合制战斗（平面互砍）：每回合玩家选 攻击/重击/防御 ===== */',
  'let fighting = false, BT = null;',
  'async function startFight(lv) {',
  '  if (fighting) return;',
  '  fighting = true;',
  '  let d;',
  '  try { d = await api("/api/shanhai/challenge/fight", { veinLv: lv }); }',
  '  catch (e) { fighting = false; toast(e.message); return; }',
  '  BT = { id: d.battleId, lv, pMax: d.pMax, gMax: d.gMax };',
  '  const mask = document.createElement("div");',
  '  mask.className = "bt-mask";',
  '  mask.innerHTML =',
  '    \'<div class="bt-top">\' +',
  '    \'<div class="bt-side"><div class="nm">你</div><div class="hpbar"><i id="pHp" style="width:100%"></i></div><div class="hpnum" id="pNum"></div></div>\' +',
  '    \'<div style="font:900 18px/1 STKaiti,serif;color:#ffd76a">VS</div>\' +',
  '    \'<div class="bt-side"><div class="nm">\' + esc(d.guardian.name) + \'</div><div class="hpbar foe"><i id="gHp" style="width:100%"></i></div><div class="hpnum" id="gNum"></div></div></div>\' +',
  '    \'<div class="bt-stage"><div class="fig" id="pFig"><div class="spr spr-hero"></div></div>\' +',
  '    \'<div style="font:900 22px/1 STKaiti,serif;color:#ffd76a">\\u2694</div>\' +',
  '    \'<div class="fig" id="gFig">\' + guardSprite(lv) + \'</div></div>\' +',
  '    \'<div class="bt-log" id="btLog"><div>第 1 回合 · 选择你的行动</div></div>\' +',
  '    \'<div class="bt-foot"><div style="display:flex;gap:8px">\' +',
  '    \'<button class="btn green" id="btnAtk" style="flex:1">\\u2694 攻击</button>\' +',
  '    \'<button class="btn green" id="btnHeavy" style="flex:1;background:linear-gradient(180deg,#d0912c,#a06a20)">\\uD83D\\uDCA5 重击</button>\' +',
  '    \'<button class="btn green" id="btnDef" style="flex:1;background:linear-gradient(180deg,#4a7a9a,#2f5470)">\\uD83D\\uDEE1 防御</button></div></div>\';',
  '  document.body.appendChild(mask);',
  '  const set = (pid, gid) => {',
  '    document.getElementById("pHp").style.width = Math.max(0, pid / BT.pMax * 100) + "%";',
  '    document.getElementById("gHp").style.width = Math.max(0, gid / BT.gMax * 100) + "%";',
  '    document.getElementById("pNum").textContent = fmt(Math.max(0, pid)) + " / " + fmt(BT.pMax);',
  '    document.getElementById("gNum").textContent = fmt(Math.max(0, gid)) + " / " + fmt(BT.gMax);',
  '  };',
  '  set(d.pHP, d.gHP);',
  '  const lock = v => ["btnAtk", "btnHeavy", "btnDef"].forEach(id => { const e = document.getElementById(id); if (e) e.disabled = v; });',
  '  const act = async action => {',
  '    if (fighting) return;',
  '    fighting = true; lock(true);',
  '    const log = document.getElementById("btLog");',
  '    try {',
  '      const r = await api("/api/shanhai/challenge/turn", { battleId: BT.id, action });',
  '      if (r.heal > 0) floatDmg(document.getElementById("pFig"), "+" + r.heal, false, "#7fe0a8");',
  '      if (r.pDmg > 0) {',
  '        const pf = document.getElementById("pFig"), gf = document.getElementById("gFig");',
  '        pf.classList.add("lunge-l"); gf.classList.add("hit");',
  '        setTimeout(() => { pf.classList.remove("lunge-l"); gf.classList.remove("hit"); }, 200);',
  '        floatDmg(gf, r.pDmg, r.pCrit);',
  '        log.innerHTML += \'<div\' + (r.pCrit ? \' class="hl"\' : \'\') + \'>第\' + r.round + \'回合：你\' + (action === "heavy" ? "【重击】" : "") + (r.pCrit ? "暴击" : "") + \'造成 \' + fmt(r.pDmg) + \' 伤害\' + (r.recoil ? \'（反震 -\' + fmt(r.recoil) + \'）\' : \'\') + \'</div>\';',
  '      } else if (r.heal > 0) {',
  '        log.innerHTML += \'<div>第\' + r.round + \'回合：你转入防御，回复 \' + r.heal + \' 生命</div>\';',
  '      }',
  '      if (r.gDmg > 0) {',
  '        const gf = document.getElementById("gFig"), pf = document.getElementById("pFig");',
  '        setTimeout(() => {',
  '          gf.classList.add("lunge-r"); pf.classList.add("hit");',
  '          setTimeout(() => { gf.classList.remove("lunge-r"); pf.classList.remove("hit"); }, 200);',
  '          floatDmg(pf, r.gDmg, false);',
  '          log.innerHTML += \'<div>\' + esc(d.guardian.name) + (r.gNote ? "【" + r.gNote + "】" : "") + \'反击造成 \' + fmt(r.gDmg) + \' 伤害</div>\';',
  '          log.scrollTop = log.scrollHeight;',
  '        }, 260);',
  '      }',
  '      set(r.pHP, r.gHP);',
  '      log.scrollTop = log.scrollHeight;',
  '      if (r.over) return finish(r.win, r.occupied);',
  '    } catch (e) {',
  '      toast(e.message || "结算失败");',
  '      if ((e.message || "").indexOf("超时") >= 0) return location.reload();',
  '    }',
  '    fighting = false; lock(false);',
  '  };',
  '  function floatDmg(el, txt, big, color) {',
  '    const f = document.createElement("div");',
  '    f.className = "floater"; f.textContent = (String(txt).startsWith("+") ? "" : "-") + txt;',
  '    f.style.color = color || (big ? "#ffd76a" : "#ff8a70");',
  '    f.style.left = (30 + Math.random() * 40) + "%"; f.style.top = "30%";',
  '    el.style.position = "relative"; el.appendChild(f);',
  '    setTimeout(() => f.remove(), 1000);',
  '  }',
  '  function finish(win, occupied) {',
  '    setTimeout(() => {',
  '      const vt = document.createElement("div");',
  '      vt.className = "verdict";',
  '      if (win) {',
  '        vt.innerHTML = \'<div class="vt" style="color:#ffd76a">占 领 成 功</div>\' +',
  '          \'<div class="vd">击败 \' + esc(G[BT.lv].name) + \'！<br>你已占领 Lv.\' + BT.lv + \' 灵脉：<br>每小时产出 \' + OUT[BT.lv] + \' 灵气，每小时结算消耗 \' + fmt(OUT[BT.lv] * 100) + \' 仙玉。<br><b>仙玉不足会自动结束占领</b>（邮件通知），可在挑战页放弃。</div>\' +',
  '          \'<button class="btn" style="width:auto;padding:11px 30px" onclick="location.reload()">返回挑战页</button>\';',
  '      } else {',
  '        vt.innerHTML = \'<div class="vt" style="color:#8a97a8">挑 战 失 败</div>\' +',
  '          \'<div class="vd">你被 \' + esc(G[BT.lv].name) + \' 击败。<br>提升装备与通关数可增强攻防，明日再战！</div>\' +',
  '          \'<button class="btn green" style="width:auto;padding:11px 30px" onclick="location.reload()">返回挑战页</button>\';',
  '      }',
  '      mask.appendChild(vt);',
  '    }, 700);',
  '  }',
  '  document.getElementById("btnAtk").onclick = () => act("attack");',
  '  document.getElementById("btnHeavy").onclick = () => act("heavy");',
  '  document.getElementById("btnDef").onclick = () => act("defend");',
  '}',
];
lines.splice(301, 383 - 301, ...NEW);
fs.writeFileSync(f, lines.join("\n"), "utf8");
console.log("replaced lines 302-383 with", NEW.length, "lines");
